### ISSUE TITLE
bug in getConnectionName

### ISSUE THREAD

**Issue by mannu1200** [request/forever-agent#33]
I am using it with newer version of node and facing problem with following code of getConnectionName function in index.js.

name = host.host + ':' + host.port + ':' + (host.localAddress ? (host.localAddress + ':') : ':')

Why appending 2 colons after port number when localAddress is not present.
name getting created for my following host object is "abcd.com:80::"
{ path: undefined,
  port: 80,
  host: 'abcd.com',
  minSockets: 10,
  maxSockets: 100,
  servername: 'abcd.com',
  _agentKey: 'abcd.com:80:',
  encoding: null 
}

**Comment by askaliuk** [comment]
+1
